name: CupidBot 1H Sync with Telegram

on:
  schedule:
    - cron: '0 * * * *'  # ⏰ Every hour
  workflow_dispatch:      # 🔘 Also lets you trigger it manually

jobs:
  run-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run CupidBot sync
        run: npm start
        env:
          CUPIDBOT_TOKEN: ${{ secrets.CUPIDBOT_TOKEN }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
